version: '3'

services:
  superset:
    image: apache/superset:latest
    container_name: superset
    restart: always
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_SECRET_KEY=thisISaSuperSecretKeyforSupersetThatIsVeryLongAndSecure123456789
      - SUPERSET_LOAD_EXAMPLES=false
      - PYTHONPATH=/app/pythonpath
      - WTF_CSRF_ENABLED=false
      - SUPERSET_WEBSERVER_ADDRESS=0.0.0.0
    volumes:
      - superset_home:/app/superset_home
    command: >
      bash -c "
        superset db upgrade &&
        (superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@superset.com --password admin || echo 'Admin user may already exist') &&
        superset init &&
        gunicorn --bind 0.0.0.0:8088 --workers 2 --worker-class gthread --threads 20 --timeout 60 'superset.app:create_app()'
      "
    networks:
      - default

volumes:
  superset_home:
